name: Performance benchmark

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-

      - name: Compile
        run: ./mvnw install -Pquick -pl '!integration-test'

      - name: Performance Benchmark
        run: ./mvnw test-compile failsafe:integration-test -pl runtime

      - name: Publish Performance Benchmark Results
        uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:v1
        if: always()
        with:
          check_name: Performance Benchmark Results
          files: "**/target/*-reports/**/TEST-*.xml"
          github_token: ${{ github.token }}