name: Integration Tests

on:
  push:
    branches: [ master, v3.X, v2.X, v1.X ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        maven_profiles: [
            "jackson-classic", "jsonb-classic",
            "jackson-reactive", "jsonb-reactive"
        ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: 'maven'

      - name: Compile
        run: ./mvnw install -Pquick -pl '!integration-test'

      - name: Integration Tests (latest - classic - jackson)
        run: ./mvnw clean verify -P${{ matrix.maven_profiles }} -pl integration-test


