name: Latest stable version compatibility with Quarkus

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        json-provider: [ "jackson-classic", "jsonb-classic", "jackson-reactive", "jsonb-reactive" ]
        quarkus-version: [ "3.0" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-

      - name: Integration Tests (latest - classic - jackson)
        env:
          LATEST_STABLE_EXTENSION_VERSION: "3.0.0"
        run: |
          echo "Checking quarkus-resteasy-problem $LATEST_STABLE_EXTENSION_VERSION with Quarkus v${{ matrix.quarkus-version }}"
          ./mvnw clean verify \
              -P${{ matrix.json-provider }},quarkus-${{ matrix.quarkus-version }} \
              -pl integration-test \
              -Dquarkus-resteasy-problem.version=$LATEST_STABLE_EXTENSION_VERSION