name: Maven CI Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-

      - name: Compile
        run: ./mvnw -B formatter:validate install -DskipTests

      - name: Unit Tests
        run: ./mvnw -B test

      - name: Integration Tests (lastest - classic - jackson)
        run: ./mvnw -B clean verify -Pjackson-classic -pl integration-test

      - name: Integration Tests (lastest - classic - jsonb)
        run: ./mvnw -B clean verify -Pjsonb-classic -pl integration-test

      - name: Integration Tests (lastest - reactive - jackson)
        run: ./mvnw -B clean verify -Pjackson-reactive -pl integration-test

      - name: Integration Tests (lastest - reactive - jsonb)
        run: ./mvnw -B clean verify -Pjsonb-reactive -pl integration-test

      - name: Integration Tests (oldest - classic - jackson)
        run: ./mvnw -B clean verify -Pjackson-classic,quarkus-1.4 -pl integration-test

      - name: Integration Tests (oldest - classic - jsonb)
        run: ./mvnw -B clean verify -Pjsonb-classic,quarkus-1.4 -pl integration-test

      - name: Integration Tests (oldest - reactive - jackson)
        run: ./mvnw -B clean verify -Pjackson-reactive,quarkus-1.12 -pl integration-test

      - name: Integration Tests (oldest - reactive - jsonb)
        run: ./mvnw -B clean verify -Pjsonb-reactive,quarkus-1.12 -pl integration-test

      - name: Publish Test Results
        uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:v1
        if: always()
        with:
          check_name: Test Results
          files: "**/target/*-reports/**/TEST-*.xml"
          github_token: ${{ github.token }}