name: PullReq Check

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-

      - name: Compile
        run: ./mvnw -B install -DskipTests

      - name: Unit Tests
        run: ./mvnw -B test

      - name: Integration Tests (oldest)
        run: |
          ./mvnw -B clean verify -Pjackson,quarkus-1.4 -pl integration-test
          ./mvnw -B clean verify -Pjsonb,quarkus-1.4 -pl integration-test

      - name: Integration Tests (lastest)
        run: |
          ./mvnw -B clean verify -Pjackson -pl integration-test
          ./mvnw -B clean verify -Pjsonb -pl integration-test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.9
        if: always()
        with:
          files: "**/target/*-reports/**/TEST-*.xml"