name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 1.4, 1.11, 1.12 ]
        json-provider: [ jsonb, jackson ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-

      - name: Compile
        run: ./mvnw -B install -DskipTests --file pom.xml

      - name: Integration tests
        run: |
          ./mvnw -B clean verify -P${{ matrix.json-provider }},quarkus-${{ matrix.version }} -pl integration-test