name: Publish to OSSRH Nexus

on:
  push:
    tags: [ v* ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: 'maven'

      - name: Setup Maven
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          servers: '[{ "id": "ossrh", "username": "${{ secrets.NEXUS_USERNAME }}", "password": "${{ secrets.NEXUS_PASSWORD }}" }]'

      - name: Package, Sign and Publish to OSSRH Nexus
        run: ./mvnw deploy -Pdeploy,quick -pl '!integration-test'
        env:
          SIGN_KEY: ${{ secrets.SIGN_KEY }}
          SIGN_KEY_PASS: ${{ secrets.SIGN_KEY_PASS }}