name: Quickstart Flow Tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        json-provider: [ "resteasy-jsonb", "resteasy-jackson" ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-

      - name: Compile and Install Extension
        run: |
          ./mvnw install -Pquick -pl '!integration-test'
          mkdir quickstart

      - name: Generate Quickstart App
        working-directory: ./quickstart
        run: |
          QUARKUS_VERSION=$(mvn -f ../pom.xml -q -Dexec.executable=echo -Dexec.args='${quarkus.version}' --non-recursive exec:exec)
          mvn io.quarkus:quarkus-maven-plugin:$QUARKUS_VERSION:create \
            -Dextensions="resteasy,${{ matrix.json-provider }}" \
            -DprojectGroupId=problem \
            -DprojectArtifactId=quarkus-resteasy-problem-playground \
            -DclassName="problem.HelloResource" \
            -Dpath="/hello"

      - name: Add extension dependency
        working-directory: ./quickstart/quarkus-resteasy-problem-playground
        run: |
          EXTENSION_VERSION=$(./mvnw -f ../../pom.xml -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          ./mvnw quarkus:add-extension -Dextensions="com.tietoevry.quarkus:quarkus-resteasy-problem:$EXTENSION_VERSION"

      - name: Run tests
        working-directory: ./quickstart/quarkus-resteasy-problem-playground
        run: |
          ./mvnw --no-transfer-progress test