name: Static Code Analysis

on:
  push:
    branches: [ master, v3.X, v2.X, v1.X ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: 'maven'

      - name: Check formatting
        run: ./mvnw formatter:validate